services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
