name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: etozhealkhipce/senior-script-kiddie-k3s/.github/workflows/deploy-app.yml@main
    with:
      app_name: sskd-backend
      app_host: admin.sskd.tech
      app_secrets: "POSTGRES_PASSWORD"
    secrets: inherit
